spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

  datasource:
    url: jdbc:postgresql://postgres/devnation
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    initialization-mode: always
