server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username:
    password: